# Generated by Django 4.0.6 on 2023-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_empresa_candidato_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
