# Generated by Django 4.0.6 on 2023-09-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_candidato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo1',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='arquivo2',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='arquivo3',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='arquivo4',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
    ]
