# Generated by Django 4.0.6 on 2023-09-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_categoria_questao_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='enunciado',
            field=models.CharField(max_length=340),
        ),
    ]
