# Generated by Django 4.0.6 on 2023-09-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_alter_questao_enunciado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='A',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='C',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='D',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='E',
            new_name='d',
        ),
    ]
