# Generated by Django 4.0.6 on 2023-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0009_rename_a_questao_a_rename_c_questao_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='arquivo1',
            new_name='atestado_acuidade_visual',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='arquivo2',
            new_name='codigo_conduta',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='arquivo3',
            new_name='comprovante_escolaridade',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='arquivo4',
            new_name='comprovante_residencia',
        ),
        migrations.AddField(
            model_name='candidato',
            name='copia_cpf',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='copia_identidade',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ctps_contrato_de_trabalhoc',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='ctps_identificação',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='declaração_participação_exame',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='instrução_candidato',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='registro_solicitação_exame',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='termos_compromissoia_cpf',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
