# Generated by Django 4.0.6 on 2023-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_rename_ctps_contrato_de_trabalhoc_candidato_ctps_contrato_de_trabalho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/'),
        ),
    ]
