# Generated by Django 4.0.6 on 2023-12-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0013_alter_candidato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
