# Generated by Django 4.0.6 on 2023-12-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0014_alter_candidato_orgao_emissor'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='nível',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Difícil', 'Difícil')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
