# Generated by Django 4.0.6 on 2024-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0015_questao_nível'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('texto', models.TextField()),
            ],
        ),
    ]
