# Generated by Django 4.0.6 on 2024-01-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_solicitação'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitação',
            new_name='Solicitacao',
        ),
    ]
