# Generated by Django 4.0.6 on 2024-01-08 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_rename_título_solicitacao_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=11)),
                ('titulo_do_certificado', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('validade', models.DateField()),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
