# Generated by Django 4.0.6 on 2024-01-08 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='identificador',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
