# Generated by Django 4.0.6 on 2024-01-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0020_certificado_identificador_alter_certificado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('Geral', 'Geral'), ('Apelação', 'Apelação'), ('Reclamação', 'Reclamação')], default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
