# Generated by Django 4.0.6 on 2024-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_solicitacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
