# Generated by Django 4.0.6 on 2024-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0022_candidato_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='declaração_participação',
            new_name='declaracao_participacao',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='instrução_candidato',
            new_name='instrucao_candidato',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='registro_solicitação_exame',
            new_name='registro_solicitacao_exame',
        ),
    ]
