# Generated by Django 4.0.6 on 2024-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0023_rename_declaração_participação_candidato_declaracao_participacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='anotacoes_cipinac',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
