# Generated by Django 4.0.6 on 2024-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_solicitacao_anotacoes_cipinac'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='protocolo',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
