# Generated by Django 4.0.6 on 2024-02-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_solicitacao_protocolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='nível',
            new_name='nivel',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
