# Generated by Django 4.0.6 on 2024-02-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0026_rename_nível_questao_nivel_alter_candidato_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_turma', models.CharField(max_length=50)),
                ('titulo_do_certificado', models.CharField(max_length=100)),
                ('data_da_prova', models.DateField()),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.turma'),
        ),
    ]
