# Generated by Django 4.0.6 on 2024-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0027_examinador_remove_candidato_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='anotacoes_cipinac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
