# Generated by Django 4.0.6 on 2024-02-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0029_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.exame'),
        ),
    ]
