# Generated by Django 4.0.6 on 2024-02-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0030_candidato_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='resposta_correta',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
