# Generated by Django 4.0.6 on 2024-02-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0031_questao_resposta_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='resposta_correta',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Difícil', 'Difícil')], max_length=50),
        ),
    ]
