# Generated by Django 4.0.6 on 2024-02-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0032_alter_questao_resposta_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='resposta_correta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50),
        ),
    ]
